var annotated_dup =
[
    [ "draw_queue", "structdraw__queue.html", "structdraw__queue" ],
    [ "gladGLversionStruct", "structgladGLversionStruct.html", "structgladGLversionStruct" ],
    [ "LodePNGColorMode", "structLodePNGColorMode.html", "structLodePNGColorMode" ],
    [ "LodePNGColorStats", "structLodePNGColorStats.html", "structLodePNGColorStats" ],
    [ "LodePNGCompressSettings", "structLodePNGCompressSettings.html", "structLodePNGCompressSettings" ],
    [ "LodePNGDecoderSettings", "structLodePNGDecoderSettings.html", "structLodePNGDecoderSettings" ],
    [ "LodePNGDecompressSettings", "structLodePNGDecompressSettings.html", "structLodePNGDecompressSettings" ],
    [ "LodePNGEncoderSettings", "structLodePNGEncoderSettings.html", "structLodePNGEncoderSettings" ],
    [ "LodePNGInfo", "structLodePNGInfo.html", "structLodePNGInfo" ],
    [ "LodePNGState", "structLodePNGState.html", "structLodePNGState" ],
    [ "LodePNGTime", "structLodePNGTime.html", "structLodePNGTime" ],
    [ "mlx", "structmlx.html", "structmlx" ],
    [ "mlx_close", "structmlx__close.html", "structmlx__close" ],
    [ "mlx_ctx", "structmlx__ctx.html", "structmlx__ctx" ],
    [ "mlx_cursor", "structmlx__cursor.html", "structmlx__cursor" ],
    [ "mlx_hook", "structmlx__hook.html", "structmlx__hook" ],
    [ "mlx_image", "structmlx__image.html", "structmlx__image" ],
    [ "mlx_image_ctx", "structmlx__image__ctx.html", "structmlx__image__ctx" ],
    [ "mlx_instance", "structmlx__instance.html", "structmlx__instance" ],
    [ "mlx_key", "structmlx__key.html", "structmlx__key" ],
    [ "mlx_key_data", "structmlx__key__data.html", "structmlx__key__data" ],
    [ "mlx_list", "structmlx__list.html", "structmlx__list" ],
    [ "mlx_mouse", "structmlx__mouse.html", "structmlx__mouse" ],
    [ "mlx_resize", "structmlx__resize.html", "structmlx__resize" ],
    [ "mlx_srcoll", "structmlx__srcoll.html", "structmlx__srcoll" ],
    [ "mlx_texture", "structmlx__texture.html", "structmlx__texture" ],
    [ "s_font", "structs__font.html", "structs__font" ],
    [ "ucvector", "structucvector.html", "structucvector" ],
    [ "vertex", "structvertex.html", "structvertex" ],
    [ "Window", "classWindow.html", "classWindow" ],
    [ "xpm", "structxpm.html", "structxpm" ]
];