name: Generate Doxygen Docs and Deploy to gh-pages Branch

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 1'  # Solo los lunes a las 6:00 UTC

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt-get install -y doxygen graphviz

      - name: Clone MLX42 from Codam
        run: |
          rm -rf lib/MLX42
          mkdir -p lib
          git clone --depth=1 https://github.com/codam-coding-college/MLX42 lib/MLX42

      - name: Generate documentation with Doxygen
        run: |
          rm -rf docs/ html/
          doxygen Doxyfile || { echo "❌ Doxygen generation failed"; exit 1; }

          if [ -d "html" ]; then
            mv html docs
          fi

          mkdir -p /tmp/artifacts
          cp -r docs /tmp/artifacts/

      - name: Deploy to gh-pages branch (force push)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin gh-pages || true
          git checkout --orphan gh-pages
          git reset --hard
          
          # Remove everything except .git directory
          find . -maxdepth 1 ! -name .git -exec rm -rf {} \; 2>/dev/null || true
          
          # Copy the generated docs
          cp -r /tmp/artifacts/docs/* .
          
          # Add, commit and push
          git add .
          git commit -m "Deploy Doxygen docs [skip ci]" || echo "✅ No changes to commit"
          git push -f origin gh-pages

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: /tmp/artifacts/docs
